### ISSUE TITLE
Missing Parcelable.ClassLoaderCreator and Parcelable.Creator

### ISSUE THREAD

**Issue by mgmclemore** [xamarin/android-api-docs#5]
These members:

http://developer.android.com/reference/android/os/Parcelable.ClassLoaderCreator.html
http://developer.android.com/reference/android/os/Parcelable.Creator.html

Are not available here:

https://developer.xamarin.com/api/type/Android.OS.Parcelable/

**Comment by davidbritch** [comment]
Closing old issue.
