### ISSUE TITLE
API docs missing for Android O

### ISSUE THREAD

**Issue by mgmclemore** [xamarin/android-api-docs#6]
We are now linking to the following Android 8.0 Oreo API docs, which need equivalent Xamarin documentation:

https://developer.android.com/reference/android/provider/FontRequest.html
https://developer.android.com/reference/android/provider/FontsContract.FontRequestCallback.html
https://developer.android.com/reference/android/provider/FontsContract.FontRequestCallback.html#onTypefaceRetrieved%28android.graphics.Typeface%29
https://developer.android.com/reference/android/provider/FontsContract.html#requestFonts(android.content.Context,%20android.provider.FontRequest,%20android.os.Handler,%20android.os.CancellationSignal,%20android.provider.FontsContract.FontRequestCallback)
https://developer.android.com/reference/android/app/Activity.html#enterPictureInPictureMode%28android.app.PictureInPictureParams%29
https://developer.android.com/reference/android/app/Activity.html#setPictureInPictureParams%28android.app.PictureInPictureParams%29

**Comment by davidbritch** [comment]
Closing old issue.
